# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-24 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parts_urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=254)),
                ('url', models.CharField(default=b'', max_length=254)),
                ('category', models.CharField(default=b'', max_length=254)),
            ],
        ),
    ]
