# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-31 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20180730_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rating', models.IntegerField(default=1)),
                ('specs_categorys', separatedvaluesfield.models.SeparatedValuesField(max_length=512)),
                ('specs_values', separatedvaluesfield.models.SeparatedValuesField(max_length=512)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_info', to='parts.parts_url')),
            ],
        ),
    ]
