# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-31 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='available_amount',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='part',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
