# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-31 13:16
from __future__ import unicode_literals

from django.db import migrations
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_auto_20180731_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='specs_categorys',
            field=separatedvaluesfield.models.SeparatedValuesField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='specs_values',
            field=separatedvaluesfield.models.SeparatedValuesField(max_length=512, null=True),
        ),
    ]
