# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-31 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_auto_20180731_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='countsold',
            field=models.IntegerField(default=1),
        ),
    ]
