# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-09 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_part_countsold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='product',
        ),
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='part',
            name='name',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='part',
            name='url',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='part',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
        migrations.DeleteModel(
            name='parts_url',
        ),
    ]
